branches:
  only:
    - /\d+\.\d+\.\d+/
language: python
python: "3.6"
env:
  - ADDON_ID=script.module.web-pdb
    BRANCH=krypton
install:
  - pip install kodi-addon-checker
  - cd frontend
  - npm install
script:
  - npm run build
  - kodi-addon-checker --branch $BRANCH $ADDON_ID
after_success:
  - cd $TRAVIS_BUILD_DIR/script.module.web-pdb/libs/web_pdb/static
  - echo "SHA256 hashes for minified files:"
  - sha256sum bundle.min.js | tee bundle.min.js.sha256
  - sha256sum styles.min.css | tee styles.min.css.sha256
  - cd $TRAVIS_BUILD_DIR
  - git add .
  - git commit -m "Add compiled static files"
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git@matrix
  - submit-addon -s -z $ADDON_ID
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the Kodi official repo
  - provider: script
    script: submit-addon -r repo-scripts -b $BRANCH -s -m --pull-request $ADDON_ID
    on:
      tags: true
notifications:
  email: false
